---
#   _____ _               _____               
#  / ____| |        /\   / ____|              
# | |    | |       /  \ | |     ___  _ __ ___ 
# | |    | |      / /\ \| |    / _ \| '__/ _ \
# | |____| |____ / ____ \ |____ (_) | | |  __/
#  \_____|______/_/    \_\_____\___/|_|  \___|

# @Website: http://cladevs.ml
# @Author: CLADevs Team

# Language Options:
#- eng
#- deu
language: eng
...